export enum ResultCodes {
  CHROMADB_CONNECTION_FAILED = "CHROMADB_CONNECTION_FAILED",
  EMBEDDING_FAILED = "EMBEDDING_FAILED",
  GENERATION_FAILED = "GENERATION_FAILED",
  NO_RELEVANT_DOCUMENTS = "NO_RELEVANT_DOCUMENTS",
  TOO_MANY_CHUNKS = "TOO_MANY_CHUNKS"
}

